#!/usr/bin/env bash
# installs and configures Nginx server

sudo apt-get update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP' 2> /dev/null
echo "Hello World!" > /var/www/html/index.html
service nginx start
