#!/usr/bin/env bash
# tests processes and signals

terminate() {
    rm /var/run/myscript.pid
    exit
}

echo "$BASHPID" > /var/run/myscript.pid
while true; do
      trap "echo I hate the kill command && terminate" SIGTERM
      trap "echo Y U no love me?!" SIGINT
      trap "terminate" SIGQUIT
      echo "To infinity and beyond"
      sleep 2
done
