#!/usr/bin/env bash
# Gives information about the school file

file_name="./school"
if [ -e "$file_name" ]; then
   echo "school file exists"
   if [ -s "$file_name" ]; then
      echo "school file is not empty"
   else
      echo "school file is empty"
   fi
else
   echo "school file does not exist"
fi
