#!/usr/bin/env bash
# configures nginx to run as the nginx user
pkill apache2
chmod 644 /etc/nginx/nginx.conf
sed -i "s/user\(.*\)/user nginx/" /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-enabled/default
sudo -u nginx service nginx restart
